### ISSUE TITLE
jquery-3.4.1 contains vulnerabilities please upgrade to 3.5.1

### ISSUE THREAD

**Issue by jgarland79** [simplecov-ruby/simplecov-html#108]
https://snyk.io/vuln/npm:jquery@3.4.1

https://github.com/simplecov-ruby/simplecov-html/blob/main/assets/javascripts/libraries/jquery-3.4.1.js

https://code.jquery.com/jquery-3.5.1.js

**Comment by PragTob** [comment]
Hi, thanks for letting us know and we'll upgrade but as these are XSS vulnerabilities you'd need to look at somebody else's malicious code (as that's the user input we got) if that is even affected by this, or am I missing another attack vector here?

**Comment by jgarland79** [comment]
@PragTob It doesn't seem to matter to our vulnerability scanner how it is used. Just that it is there and the code is flagged as vunlerable. :(

**Comment by PragTob** [comment]
Of course it doesn't matter for it :D So, your problem is more that your security scanner nags you about it than the actual security risk.

**Comment by snarfmason** [comment]
@PragTob hey, if I made a PR to update to jquery 3.5.1 would you accept the patch?

**Comment by neilsy** [comment]
@PragTob Do you have time to check this out?  #115 
It would help my team a lot if we could comply with my company's security policies without begging for exceptions!  Probably there are many others in the same boat now, with off-the-shelf scans becoming standard.
