### ISSUE TITLE
Missing asset referenced

### ISSUE THREAD

**Issue by adi-pen** [simplecov-ruby/simplecov-html#109]
I'm trying to generate an inline-html report using an external JS library. Encountered an issue due to a missing asset that is referenced in the code.

https://github.com/simplecov-ruby/simplecov-html/blob/d2685887446ad7ae25560c3ceda31b5a598b9817/views/layout.erb#L9

Filing an issue in case you'd like to fix this.

**Comment by adi-pen** [comment]
Will be solved if #107 is merged.

**Comment by amatsuda** [comment]
fixed via #123
