### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by lukasfroehlich1** [simplecov-ruby/simplecov-html#136]
There have been a lot of great fixes since the last release, can we make a new release? https://github.com/simplecov-ruby/simplecov-html/compare/v0.12.3...main

Thanks!

**Comment by amatsuda** [comment]
@colszowka I'd love to work on this (if no one else wants to). Could you please add me to the gem owners?

**Comment by adambonsu** [comment]
@amatsuda thank you for resolving the [jquery version security issue](https://github.com/simplecov-ruby/simplecov-html/commit/37f8470c0b71543f1aae857e6e37506fbbe401cf). Looking forward to the new release

**Comment by amatsuda** [comment]
Done! Enjoy! https://rubygems.org/gems/simplecov-html/versions/0.13.1
