### ISSUE TITLE
Feature proposal: Inline assets

### ISSUE THREAD

**Issue by eins78** [simplecov-ruby/simplecov-html#33]
In the context where we use `simplecov`(`-html`), it is much more practical to have the result in a single HTML file, with the assets included in base64-encoded form.

I implemented this in a quick and dirty way (using sprockets), but it works. 
You can have a look at it here: https://github.com/eins78/simplecov-html/commit/939548dabd76d626565ff25f53eda21dd0f8417a

I would not send this commit as a PR, but if there is general interest in this feature it could be cleaned up.

---

btw: 
A quick comparison of file sizes shows that in our case it actually gets smaller (I guess because only referenced assets are included).
- index.html + ./assets: 584K
- index.html with inline: 564K

**Comment by rthbound** [comment]
+1

**Comment by rthbound** [comment]
@eins78 any chance you could add a spec for this?

**Comment by jeromegn** [comment]
I wish this was available. Can you PR your code? I'm sure they'd be more tempted to add it if it was as simple as a click of a button.

**Comment by Galathius** [comment]
:+1:

**Comment by byucesoy** [comment]
This would indeed be very useful. Especially for CI/CD systems which allow uploading single HTML file.

**Comment by PragTob** [comment]
Hi there,

indeed this would be a great feature. Alas, right now when I'm working on simplecov it's more on the fixing bugs and finishing up existing features vs. adding new features front :)

So a PR would be welcome. Otherwise, give me time to add it :)

Cheers,
Tobi

**Comment by emptyflask** [comment]
https://github.com/colszowka/simplecov/issues/741 would be resolved by this

**Comment by frankh** [comment]
@PragTob I've opened a PR for this here: https://github.com/simplecov-ruby/simplecov-html/pull/107 let me know if you'd like any changes
