### ISSUE TITLE
Feature proposal: line number anchors

### ISSUE THREAD

**Issue by jantman** [simplecov-ruby/simplecov-html#49]
Using simplecov-html reports while doing active development is a bit painful right now:

1. I'm looking at the coverage report for a file, and find some missing lines. Let's say, hypothetically, they're lines 503-505.
2. Add tests that I think cover those lines and re-run my rspec rake task.
3. Refresh the coverage report in my browser and... I'm back at the top of the page and need to scroll to line 503 again.

My suggestion is to implement what some other HTML coverage generators do (i.e. Python's [coverage](https://coverage.readthedocs.io/en/coverage-4.2/index.html) package) - or, for that matter, GitHub when viewing source files or gists - and make each line number [a named anchor and link to that anchor](http://nedbatchelder.com/files/sample_coverage_html/cogapp_test_cogapp_py.html#n201) so that users can save their location in the file.

**Comment by nishidayuya** [comment]
@jantman I implemented this issue in #106 ! :smile:
